#!/usr/bin/env python

import sys
import rospy
from qt_robot_interface.srv import *
from qt_vosk_app.srv import *
import wikipedia

if __name__ == '__main__':
    
    # Initialisation du noeud ROS
    rospy.init_node('qt_robot_speech')
    rospy.loginfo("Hi") 
    
    speechSay = rospy.ServiceProxy('/qt_robot/speech/say', speech_say)
    recognize = rospy.ServiceProxy('/qt_robot/speech/recognize', speech_recognize)
    rospy.wait_for_service('/qt_robot/speech/say')
    rospy.wait_for_service('/qt_robot/speech/recognize')


    speechSay("Bonjour! Tu veux faire une recherche? ")
    resp = recognize("fr_FR", [], 0)
    print(resp.transcript)
    rospy.loginfo("I got: %s", resp.transcript)
    if resp.transcript == "oui":
        speechSay("Donne moi un mot clé")
        key_word = recognize("fr_FR", [], 0).transcript
        demande = key_word
        wikipedia.set_lang("fr")
        liste_recherche = wikipedia.search(demande)
        recherche = liste_recherche[0]

        # finding result for the search
        # sentences = 2 refers to numbers of line
        result = wikipedia.summary(recherche, sentences = 4, auto_suggest=False)
        speechSay("Voici ce que j'ai trouvé sur wikipedia: %s ", result)

    try:
        
        #The code is repeated until the user taps ctrl+C 
        rospy.spin()
    except KeyboardInterrupt:
        pass
    
    rospy.loginfo("Finished!")
